# Generated by Django 4.1.13 on 2024-08-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='arrival_time',
        ),
    ]
