# Generated by Django 5.1 on 2024-08-09 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_remove_customuser_is_active_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 21, 5, 30, 403614)),
        ),
    ]
