# Generated by Django 5.1 on 2024-08-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_rename_is_verified_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
