# Generated by Django 5.1 on 2024-08-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_remove_customuser_verification_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
