# Generated by Django 4.1.13 on 2024-08-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DRIVER', 'Driver'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=10),
        ),
    ]
